FROM golang:1.12-alpine

RUN apk update && apk add gcc g++

RUN mkdir -p /go/src/github.com/porthos-rpc/porthos-playground
ADD . /go/src/github.com/porthos-rpc/porthos-playground
WORKDIR /go/src/github.com/porthos-rpc/porthos-playground

VOLUME /go/src/github.com/porthos-rpc/porthos-playground/dist

CMD ["go","build","-o","/go/src/github.com/porthos-rpc/porthos-playground/dist/playground","."]
